#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, gaps, multiple
#    chains per unit cell

#  does not have:  non-standard residues, ligands

echo "Running non-LES test on 1of1A"
phenix.AmberPrep 1of1A.pdb minimise=off use_reduce=False > non-les.log 2>&1

./dacdif non-les/4phenix_1of1A.pdb 4phenix_1of1A.pdb
status=$?
./dacdif non-les/4amber_1of1A.prmtop 4amber_1of1A.prmtop
status=$(($status + $?))
./dacdif non-les/4amber_1of1A.rst7 4amber_1of1A.rst7
status=$(($status + $?))
./dacdif non-les/4amber_1of1A.order 4amber_1of1A.order
status=$(($status + $?))
./dacdif non-les/non-les.log non-les.log
status=$(($status + $?))

/bin/rm -f 1of1A_4tleap_renum.txt 1of1A_uc.pdb tleap_uc.in

exit $status
