#!/bin/sh

#  simple test case: has a modified residue, with a non-standard 
#  connectivity, and non-covalent ligands

#  make the tests independent of whether the user has the amber library
#  mounted or not:
unset AMBER_LIBRARY_DIR     

echo "Running non-LES test on 1dy5:"
phenix.AmberPrep 1dy5.pdb minimise=amber_all > non-les.log 2>&1

#./dacdif non-les/4phenix_1dy5.pdb 4phenix_1dy5.pdb
#status=$?
./dacdif non-les/4amber_1dy5.prmtop 4amber_1dy5.prmtop
status=$(($status + $?))
#./dacdif non-les/4amber_1dy5.rst7 4amber_1dy5.rst7
#status=$(($status + $?))
./dacdif non-les/4amber_1dy5.order 4amber_1dy5.order
status=$(($status + $?))
./dacdif non-les/non-les.log non-les.log
status=$(($status + $?))

/bin/rm -f 1dy5.min.out ACT.* IPA.* SO4.*  1dy5_uc.pdb 4phenix_1dy5.pdb \
    4amber_1dy5.rst7

exit $status
