#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, gaps, multiple
#    chains per unit cell

#  does not have:  non-standard residues

echo "Running LES test on 1aho with a gap:"
phenix.AmberPrep 1dy5.pdb minimise=amber_all LES=true > les.log 2>&1

./dacdif les/4phenix_1dy5.pdb 4phenix_1dy5.pdb
status=$?
./dacdif les/4amber_1dy5.prmtop 4amber_1dy5.prmtop
status=$(($status + $?))
./dacdif les/4amber_1dy5.order 4amber_1dy5.order
status=$(($status + $?))
./dacdif les/1dy5.min.out 1dy5.min.out
status=$(($status + $?))
./dacdif les/les.log les.log
status=$(($status + $?))

/bin/rm -f 4amber_1dy5.LES.pdb 4amber_1dy5.rst7

exit $status
