#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, multiple
#    chains per unit cell, non-standard residues, insertion codes

#  does not have:  gaps
#  also of interest: leaving out the use_reduce=False is OK, but gives
#           slightly different results

echo "Running non-LES test on 3cfb:"
unset AMBER_LIBRARY_DIR
phenix.AmberPrep 3cfb.pdb use_reduce=False > non-les.log 2>&1

status=0

./dacdif non-les/4phenix_3cfb.pdb 4phenix_3cfb.pdb
status=$(($status + $?))
#./dacdif non-les/4amber_3cfb.prmtop 4amber_3cfb.prmtop
#status=$(($status + $?))
./dacdif non-les/4amber_3cfb.order 4amber_3cfb.order
status=$(($status + $?))
#./dacdif non-les/non-les.log non-les.log
#status=$(($status + $?))

if false; then

# 3cfb test currently (9mar17) exceeds the MAXLESTYP variable in sander

echo "Running LES test on 3cfb:"
phenix.AmberPrep 3cfb.pdb use_reduce=False minimise=amber_all LES=true > les.log 2>&1

./dacdif les/4phenix_3cfb.pdb 4phenix_3cfb.pdb
./dacdif les/4amber_3cfb.prmtop 4amber_3cfb.prmtop
./dacdif les/4amber_3cfb.rst7 4amber_3cfb.rst7
./dacdif les/3cfb.min.out 3cfb.min.out
./dacdif les/addles.in addles.in
./dacdif les/addles.out addles.out
./dacdif les/les.log les.log

fi

./dacdif non-les/SPB.mol2 SPB.mol2
status=$(($status + $?))
./dacdif non-les/SPB.frcmod SPB.frcmod
status=$(($status + $?))

/bin/rm -f SPB.cif SPB.pdb 3cfb_uc.pdb 4amber_3cfb.rst7 \
    tleap_uc.in 4amber_3cfb.prmtop non-les.log

exit $status
