#!/bin/sh

#  run several simple tests of Amber preparation and refinement on 3cfb:
#  this exercise the ability to handle non-standard ligands

unset AMBER_LIBRARY_DIR
/bin/rm -rf SPB.mol2 GOL.mol2

phenix.pdbtools keep="chain L" 3cfb.pdb
cp 3cfb_modified.pdb 3cfb.pdb

./test_AmberPrep
status=$?

./test_phenix.refine
status=$(($status + $?))

#  as of May, 2020, the LES-created PDB files don't handle insertion
#  codes correctly, so these tests are commented out.

#./test_AmberPrep_LES
#status=$(($status + $?))

#./test_phenix.refine_LES
#status=$(($status + $?))

/bin/rm -f amber_002.def

exit $status
