#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, gaps, multiple
#    chains per unit cell

#  does not have:  non-standard residues

echo "Running non-LES test on 1aho with a gap:"
phenix.AmberPrep 1aho.pdb minimise=amber_all > non-les.log 2>&1

./dacdif non-les/4phenix_1aho.pdb 4phenix_1aho.pdb
./dacdif non-les/4amber_1aho.prmtop 4amber_1aho.prmtop
./dacdif non-les/4amber_1aho.rst7 4amber_1aho.rst7
./dacdif non-les/1aho.min.out 1aho.min.out
./dacdif non-les/non-les.log non-les.log

echo "Running LES test on 1aho with a gap:"
phenix.AmberPrep 1aho.pdb minimise=amber_all LES=true > les.log 2>&1

./dacdif les/4phenix_1aho.pdb 4phenix_1aho.pdb
./dacdif les/4amber_1aho.prmtop 4amber_1aho.prmtop
./dacdif les/4amber_1aho.rst7 4amber_1aho.rst7
./dacdif les/1aho.min.out 1aho.min.out
./dacdif les/les.log les.log
