#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, gaps, multiple
#    chains per unit cell

#  does not have:  non-standard residues

echo "Running LES test on 1aho with a gap:"
phenix.AmberPrep 1aho.pdb minimise=amber_all LES=true use_reduce=False > les.log 2>&1

./dacdif les/4phenix_1aho.pdb 4phenix_1aho.pdb
status=$?
./dacdif les/4amber_1aho.prmtop 4amber_1aho.prmtop
status=$(($status + $?))
./dacdif les/4amber_1aho.order 4amber_1aho.order
status=$(($status + $?))
./dacdif -a 0.003 les/4amber_1aho.rst7 4amber_1aho.rst7
status=$(($status + $?))
./dacdif les/1aho.min.out 1aho.min.out
status=$(($status + $?))
./dacdif les/les.log les.log
status=$(($status + $?))
./dacdif les/addles.in addles.in
status=$(($status + $?))

/bin/rm -f 1aho_4tleap_renum.txt 1aho_uc.pdb tleap_uc.in addles.log

exit $status
