#!/bin/sh

#  simple test case: has alternate conformers, ss bonds, gaps, multiple
#    chains per unit cell

#  does not have:  non-standard residues, ligands

echo "Running non-LES test on 1aho with a gap:"
phenix.AmberPrep 1aho.pdb minimise=amber_all > non-les.log 2>&1

./dacdif non-les/4phenix_1aho.pdb 4phenix_1aho.pdb
status=$?
./dacdif non-les/4amber_1aho.prmtop 4amber_1aho.prmtop
status=$(($status + $?))
./dacdif non-les/4amber_1aho.rst7 4amber_1aho.rst7
status=$(($status + $?))
./dacdif non-les/4amber_1aho.order 4amber_1aho.order
status=$(($status + $?))
awk 'NF!=6' 1aho.min.out > 1aho.min.out6
./dacdif non-les/1aho.min.out6 1aho.min.out6
status=$(($status + $?))
./dacdif non-les/non-les.log non-les.log
status=$(($status + $?))

/bin/rm -f 1aho.min.out 1aho_4tleap_renum.txt

exit $status
